// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {fetcher} from '../models';

export function CollapseWindow():Promise<void>;

export function ExpandWindow(arg1:number,arg2:number):Promise<void>;

export function GetConfig():Promise<Record<string, any>>;

export function OpenLoginPage(arg1:string):Promise<void>;

export function Refresh():Promise<Array<fetcher.QuotaResult>>;

export function SaveBallPosition(arg1:number,arg2:number):Promise<void>;

export function SaveConfig(arg1:string,arg2:string,arg3:string,arg4:number):Promise<void>;

export function TestConnection(arg1:string):Promise<string>;
