// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CollapseWindow() {
  return window['go']['main']['App']['CollapseWindow']();
}

export function ExpandWindow(arg1, arg2) {
  return window['go']['main']['App']['ExpandWindow'](arg1, arg2);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function OpenLoginPage(arg1) {
  return window['go']['main']['App']['OpenLoginPage'](arg1);
}

export function Refresh() {
  return window['go']['main']['App']['Refresh']();
}

export function SaveBallPosition(arg1, arg2) {
  return window['go']['main']['App']['SaveBallPosition'](arg1, arg2);
}

export function SaveConfig(arg1, arg2) {
  return window['go']['main']['App']['SaveConfig'](arg1, arg2);
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}
